### ISSUE TITLE
AppInspector errors when trying to set output filetype as HTML

### ISSUE THREAD

**Issue by localacct** [microsoft/ApplicationInspector#75]
**Describe the bug**
When trying to output the file as html, I will see that AppInspector tries looking for a non existent file "html/index.html" inside the current folder where the command is run.

Command line
````
dotnet /path/to/AppInspector.dll analyze -s file.c -f html
````

Error message in log.txt
````
Runtime error: Could not find a part of the path "/current/path/to/source/code/files/html/index.html"
````

If I tried the following, I see another error message

````
dotnet /path/to/AppInspector.dll analyze -s file.c -f html -o ./output.html
````

Error message in log.txt
````
Runtime error: Object reference not set to an instance of an object
````

**To Reproduce**
Try to analyze a file and select the filetype as html and use either of the command line arguments listed above. There are no issues setting the output filetype as JSON or Text.

**Expected behavior**
AppInspector should be able to output a proper html file

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS 10.14.6 Mojave
 - Browser Google Chrome
 - Version 79.0.3945.117

**Smartphone (please complete the following information):**

**Additional context**

**Comment by guyacosta** [comment]
Verified.  The tool doesn't expect an output or -o argument for the html format since the file is managed by the tool itself.  I've fixed it as follows: if an output parameter is specified for the html format the user will see a warning that the -o argument will be ignored for the html format type as designed.  To see the HTML output -don't include an output argument.  For json or text formats the -o is applicable and the output can be directed as desired.  A fix to check for this non-working combination has been added and the next build will have the fix.

**Comment by localacct** [comment]
Hi @guyacosta

Even if I were to only use the following, without any output arguments, it will still show the error

````
dotnet /path/to/AppInspector.dll analyze -s file.c
````

````
Runtime error: Could not find a part of the path '/path/to/source_code/files/html/index.html'
````
